const SLOT_CONTENTS_PRESETS = new Map([
    ['Cats, Assorted', [
        'Sebastian the Nocturnal Smotherer',
        'Calliope the Yowler',
        'Love-Sickened Seneschal',
        'The Minister of War',
        'The Minister of Enigmas',
        'The Minister of Culture',
        'The Minister of State Affairs',
        'Starveling Cat',
        'Pink-Painted Cat',
        'Horatio, Finest of His Lineage',
        'Grubby Kitten',
        'Gustav the Ankle Weaver',
        'Rubbery Feline',
        'August Feline',
        'Corresponding Ocelot',
        'Benvolio the Bacon Thief',
        'Freya, Scourge of Fragile Ornaments',
        'Midnight Matriarch',
        'Midnight Matriarch of the Menagerie of Roses',
        'Bengal Tigress',
        'Extravagantly-Titled Tigress',
        'Tomb-Lion',
        'Parabolan Panther',
        'Parabolan Kitten',
        'Wretched Mog',
        'Princeling of the Wakeful Court',
        'Morally and Physically Flexible Rubbery Cat',
        'A Short-Tempered Shorthair',
        'Lyon Pursuivant of Arms Extraordinary'
    ]],
    ['Very Good Boys', [
        'Slavering Dream-Hound',
        'Disappointing Marsh-Wolf',
        'Hungover Terrier',
        'Haunted-Looking Dog',
        'Maverick Bloodhound',
        'A Bedraggled, Forlorn Fox',
        'Spindlewolf',
        'Elongated Spindlewolf',
        'Surveilling Spindlewolf',
        'Brachiating Spindlewolf',
        'Perspicacious Lurcher'
    ]],
    ['Items of Renown', [
        'Oneiric Key',
        'The Place Where they Bury the Bodies',
        'One Who Pulls the Strings',
        'Infernal Vinification Apparatus',
        'Gleaming Buttons',
        'Location of an Underground Organ',
        "Most Humbling Expression of Her Majesty's Esteem",
        'Beatific Stone',
        'Unexploded Mine',
        'The Great Game',
        'Newly-Born Frost-Moth',
        'What Might Be A Thunderbolt'
    ]],
    ['Catch the Neathbow', [
        'Irrigo-filled Mirrorcatch Box',
        'Cosmogone-filled Mirrorcatch Box',
        'Gant-filled Mirrorcatch Box',
        'Peligin-filled Mirrorcatch Box',
        'Violant-filled Mirrorcatch Box',
        'Viric-filled Mirrorcatch Box'
    ]]
]);

const DEFAULT_PRESET_KEY = 'Cats, Assorted';
