const SLOT_CONTENTS_PRESETS = new Map([
    ['Cats, Assorted', [
        'Sebastian the Nocturnal Smotherer',
        'Calliope the Yowler',
        'Love-Sickened Seneschal',
        'The Minister of War',
        'The Minister of Enigmas',
        'The Minister of Culture',
        'The Minister of State Affairs',
        'Starveling Stole',
        'Starveling Cat',
        'Pink-Painted Cat',
        'Horatio, Finest of His Lineage',
        'Grubby Kitten',
        'Gustav the Ankle Weaver',
        'Rubbery Feline',
        'August Feline',
        'Corresponding Ocelot',
        'Benvolio the Bacon Thief',
        'Freya, Scourge of Fragile Ornaments',
        'Midnight Matriarch',
        'Midnight Matriarch of the Menagerie of Roses',
        'Bengal Tigress',
        'Extravagantly-Titled Tigress',
        'An Uneasy Alliance with an Exiled Tiger',
        'Tomb-Lion',
        'Parabolan Panther',
        'Parabolan Kitten',
        'Lovingly Be-Ribboned Kitten',
        'Wretched Mog',
        'Princeling of the Wakeful Court',
        'Morally and Physically Flexible Rubbery Cat',
        'A Short-Tempered Shorthair',
        'Lyon Pursuivant of Arms Extraordinary',
        'Inquisitive Lamp-cat',
        'Feline Pariah',
    ]],
    ['Very Good Boys', [
        'Slavering Dream-Hound',
        'Disappointing Marsh-Wolf',
        'Hungover Terrier',
        'Haunted-Looking Dog',
        'Maverick Bloodhound',
        'A Bedraggled, Forlorn Fox',
        'Spindlewolf',
        'Elongated Spindlewolf',
        'Surveilling Spindlewolf',
        'Brachiating Spindlewolf',
        'Perspicacious Lurcher'
    ]],
    ['Items of Renown', [
        'Oneiric Key',
        'The Place Where they Bury the Bodies',
        'One Who Pulls the Strings',
        'Infernal Vinification Apparatus',
        'Gleaming Buttons',
        'Location of an Underground Organ',
        "Most Humbling Expression of Her Majesty's Esteem",
        'Beatific Stone',
        'Unexploded Mine',
        'The Great Game',
        'Newly-Born Frost-Moth',
        'What Might Be A Thunderbolt'
    ]]
    ,
    ['Whitsun', [
        'Young Terror Bird',
        'Full-Grown Terror Bird',
        'Iron-Toothed Terror Bird',
        'Double-Headed Terror Bird',
        'Birdskin Gloves',
        'Iron-Lung Bagpipes',
        'Aurochs',
        'Carnivorous Aurochs',
        'Dream-dwelling Carnivorous Aurochs',
        'Reflected Minotaur',
        'Aurochs-Fur Coat',
        'Skein of Silvered Catgut',
        'Untrained Lyrebird',
        'Operatic Lyrebird',
        'Lyrebird Educated in Three Schools',
        'Unquenchable Firebird',
        'Tuneful Hat',
        'Coolflame Quill',
        'Suspicious Iguana',
        'Amber Iguana',
        'Warm-hearted Amber Iguana',
        'Rubbery Dragon',
        'Iguana-Skin Boots',
        'Resinous Pyrophone',
        'Quizzical Squirrel',
        'Acute Squirrel',
        'Acicular Squirrel',
        'Transfixing Squirrel',
        'Honed Ushanka',
        'Telsonic Signet',
        'Spindlewolf',
        'Elongated Spindlewolf',
        'Surveilling Spindlewolf',
        'Brachiating Spindlewolf',
        'Vigilant Chitin-Fur Boots',
        'Russet Brachiator',
        'Unerring Elver',
        'Abyssal Sawtooth',
        'Immaculate Eel',
        'Uttermost Eel',
        'Moray Heels',
        'Flexile Sabre',
        'Prismatic Squidling',
        'Canny Cuttlefish',
        'Violantly Mercantile Cuttlefish',
        'Inculcating Kraken',
        'Mesmeric Parasol',
        'Cephalopod Satchel',
        'Copper-Speckled Crustacean',
        'Dilly',
        'Mycological Bullfrog',
        'Voracious Lamp-Eye',
        'Elegiac Cockatoo',
        'Imminent Falcon',
        'Burbling Wolfhound',
        'Exuberant Batling'
    ]]
]);

const DEFAULT_PRESET_KEY = 'Cats, Assorted';
